version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./backend/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    # ports:
    #   - "3306:3306"

  api:
    build: ./duckDataAPI
    volumes:
      - ./backend/db:/var/lib/mysql
    restart: always
    ports:
      - 8080:3000

